baseurl: /
languageCode: en-us
title: Zhiming Lu
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 2
    - name: "Publications"
      url: "/about/"
      weight: 4
    - name: "Experiences"
      url: "/categories/"
      weight: 6
    - name: ""
      url: "/tags/"
      weight: 8


params:
  description: ""
  footer: "&copy; [Zhiming Lu](https://zhiminglu.com) | [Email](luzhm6@mail2.sysu.edu.cn) | [Github](https://github.com/)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
